# Site
site_name: Личные заметки
site_author: Vladimir Penzin
site_url: https://github.com/ForceFledgling/ForceFledgling
copyright: 2024, Vladimir Penzin

# Repo
courses_url: /courses
notes_url: /notes
repo_url: https://github.com/ForceFledgling/ForceFledgling
repo_name: github
edit_uri: blob/main/docs/

extra:
  generator: false  # не отображать MkDocs copyright
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/vpotd
      name: Vladimir Penzin on Telegram
    - icon: fontawesome/brands/github
      link: https://github.com/ForceFledgling
      name: Vladimir Penzin on GitHub

extra_css:
  - assets/styles/extra.css

theme:
  name: material
  favicon: assets/images/logo.svg
  logo: assets/images/logo.svg
  custom_dir: docs/overrides
  language: ru
  features:
    - content.action.edit           # кнопка редактирования
    - navigation.tabs               # меню
    - navigation.tabs.sticky        # меню - прибиваем к верху
    - navigation.footer             # навигация в футере
    - navigation.instant.progress   # отображает вверху прогресс загрузки страницы (для медленных соединений)
    - navigation.top                # добавляет кнопку прокрутки вверх
    - search.highlight              # выделяет вхождения поиска после перехода
    - search.share                  # позволяет скопировать в буфер поисковый URL
  palette:
    primary: white
    accent: cyan
  icon:  # Иконки следующей и предыдущей страниц
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil

plugins:
  - search:
  - macros:
      module_name: macros
      on_error_fail: true
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            heading_level: 4
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_bases: false
            show_inheritance_diagram: true
            find_stubs_package: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Главная:
    - Главная: index.md
    - Каталог курсов: courses.md
    - Каталог заметок: notes.md

  - Dev:
      - Обзор: modules/dev/index.md
      - Жизненный цикл разработки ПО:
        - SDLС (этапы, практики, методологии): modules/dev/apps/sdlc.md
        - Работа с требованиями (типы требований, DoD, DoR, декомпозиция и оценка): modules/dev/apps/req.md
        - CI/CD (Continuous Integration и Continuous Delivery): modules/dev/apps/cicd.md
        - Releases (типы, отличия): modules/dev/apps/releases.md
        - Управлению разработкой (Agile, Scrum, aтрибуты, Канбан): modules/dev/apps/agile.md
      - Структуры данных и алгоритмы: modules/dev/structures/index.md
      - Software Design: modules/dev/softdesign/index.md
      - Архитектура: modules/dev/arch/index.md
      - API: modules/dev/api/index.md
      - System Design: modules/dev/sysdesign/index.md
      - Web безопасность: modules/dev/websec/index.md
      - Обеспечение качества: modules/dev/qos/index.md
      - Оптимизация и производительность: modules/dev/performance/index.md
      - Frontend Development: modules/dev/front/index.md
      - Базы данных: modules/dev/db/index.md
      - Soft Skills: modules/dev/softskills/index.md
  
  - Git:
    - Обзор: modules/git/index.md

  - Python:
    - Обзор: modules/python/index.md
    - Основы Python:
      - Типы и структуры данных: modules/python/base/types-and-structures.md
      - Итераторы, генераторы: modules/python/base/iterators-generators.md
      - Менеджер контекста:  modules/python/base/context.md
      - Исключения: modules/python/base/exceptions.md
    - ООП в Python:
      - Объекты, области видимости: modules/python/oop/intro.md
      - Стандартные модули и функции: modules/python/oop/intro.md
      - Дескрипторы: modules/python/oop/intro.md
      - Классы, наследование, метаклассы: modules/python/oop/intro.md
    - Фреймворки и библиотеки:
      - Типы и различия: modules/python/libs/intro.md
      - Web: modules/python/libs/web.md
      - ORM: modules/python/libs/orm.md
      - Math: modules/python/libs/math.md
    - Многопоточность и асинхронность: modules/python/parallelizm.md
    - Логирование, мониторинг: modules/python/logging.md
    - Базы данных: modules/python/db.md
    - Тестирование и контроль качества кода: 
      - Пирамида тестирования и умение писать тесты: modules/python/tests/intro.md
      - Pylint, Pytest, PEP-8, PEP-257: modules/python/tests/linters.md
    - Отладка и профилирование:
      - Cython: modules/python/debug/cython.md
      - Numba: modules/python/debug/numba.md
      - Условные точки останова: modules/python/debug/points.md
      - Трассировка: modules/python/debug/trace.md
      - Отладка многопоточного и асинхронного кода: modules/python/debug/async.md
      - Отладка на уровне интерпретатора: modules/python/debug/interpreter.md

  - DevOps:
    - Обзор: modules/devops/index.md